# Generated by Django 4.2.5 on 2023-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miningservices',
            fields=[
                ('idservices', models.AutoField(primary_key=True, serialize=False)),
                ('nameservices', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'miningservices',
                'managed': False,
            },
        ),
    ]
