# Generated by Django 4.2.5 on 2023-11-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningservices',
            options={},
        ),
    ]
