# Generated by Django 4.2.5 on 2023-11-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_miningservices_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miningservices',
            options={'managed': False},
        ),
    ]
