# Generated by Django 4.2.5 on 2023-11-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_requestservice_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestService',
        ),
    ]
