# Generated by Django 4.2.7 on 2024-02-08 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 1, 51, 388510, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
